import React, { useState } from 'react'
import { Platform, Pressable, ScrollView, Text, View } from 'react-native'
import { ChevronDown, ChevronRight, FileText, Shield } from 'lucide-react-native'
import { C, F } from '../tokens'

// Terms & Conditions and Privacy Policy. Shown as expandable cards in Settings
// (LegalDocs) and as standalone public pages at /terms and /privacy (LegalPage).
// Content reflects what the app ACTUALLY does: a Supabase-backed goal/social app
// whose AI features run through Anthropic and whose emails send via Resend.
// NOTE: this is written to be honest and specific, not as a substitute for a
// lawyer's review before a public launch.

export const LAST_UPDATED = 'July 2026'

export const TERMS = [
  {
    h: '1. Acceptance',
    b: 'NorthStar is a personal goal-setting and coaching app. By creating an account or using the app, you agree to these Terms. If you do not agree, please do not use NorthStar.',
  },
  {
    h: '2. Who can use it',
    b: 'You must be at least 13 years old to use NorthStar. If you are under the age of majority where you live, you may only use it with the involvement of a parent or guardian. You are responsible for keeping your password secure and for activity on your account.',
  },
  {
    h: '3. Your content',
    b: 'The goals, dreams, posts, messages, and other content you create are yours. By posting to the public feed or to friends, you grant NorthStar permission to store and display that content to the audience you choose. You are responsible for what you post; do not post anything unlawful, harassing, hateful, or that infringes someone else’s rights.',
  },
  {
    h: '4. AI coaching (Nova)',
    b: 'Nova, your roadmaps, dream readings, and reminders are generated by AI. They are for motivation and planning only — they are not professional, medical, legal, financial, or mental-health advice. AI can be wrong or incomplete; use your own judgement and consult a qualified professional for important decisions.',
  },
  {
    h: '5. Community conduct',
    b: 'When you add friends, post updates, or send messages, treat others with respect. We may remove content or suspend accounts that abuse the community, spam other users, or violate these Terms.',
  },
  {
    h: '6. Availability',
    b: 'We work to keep NorthStar running, but the app is provided “as is” without warranties. Features may change, and the service may occasionally be unavailable. We are not liable for lost data or missed goals arising from downtime, errors, or your use of the app, to the fullest extent permitted by law.',
  },
  {
    h: '7. Ending your use',
    b: 'You can delete your account at any time from Settings, which permanently removes your data. We may suspend or terminate accounts that violate these Terms.',
  },
  {
    h: '8. Changes',
    b: `We may update these Terms as the app evolves. When we make material changes, we’ll update the date shown here. Continued use after an update means you accept the revised Terms. Last updated: ${LAST_UPDATED}.`,
  },
]

export const PRIVACY = [
  {
    h: '1. The short version',
    b: 'NorthStar stores what you need for the app to work — your account, your goals, your progress, and anything you choose to share. We do not sell your personal data. You can view what Nova remembers, and delete your whole account, from Settings.',
  },
  {
    h: '2. What we collect',
    b: 'Account details you provide (name, username, email, and optionally age, gender, bio, and photo). Your goals, dreams, roadmaps, streaks, and daily tasks. Your chats with Nova and the facts Nova distils into its long-term memory. Social activity you create: posts, likes, friends, and direct messages. Basic technical data needed to run the service.',
  },
  {
    h: '3. How your data is used',
    b: 'To provide the core app — saving your goals and progress, syncing across your devices, powering Nova’s coaching, and letting you connect with friends. We use the audience you pick for each post (public or friends-only) to decide who can see it. We do not use your private content for advertising.',
  },
  {
    h: '4. Who we share it with',
    b: 'We use a small number of trusted service providers to run NorthStar: Supabase (secure database, authentication, and file storage), Anthropic (the AI that powers Nova — your messages and goal text are sent there to generate responses), and Resend (to deliver account emails such as confirmations and password resets). These providers process data on our behalf under their own security and privacy commitments; they are not permitted to use it for their own purposes.',
  },
  {
    h: '5. Visibility & other users',
    b: 'Your profile visibility (public or private) and each post’s audience control what other users can see. A private profile is visible only to friends you accept. Posting to the public feed makes that post — and your name and username — visible to anyone on NorthStar. Access is enforced by database security rules, not just the app screens.',
  },
  {
    h: '6. Data retention & deletion',
    b: 'We keep your data while your account is active. Deleting your account from Settings permanently removes your profile, goals, progress, memory, posts, and messages. You can also clear Nova’s memory on its own at any time under “Nova’s Memory”.',
  },
  {
    h: '7. Security',
    b: 'Data is transmitted over encrypted connections and protected by per-user access rules so one account cannot read another’s private data. No system is perfectly secure, but we take reasonable measures to protect your information.',
  },
  {
    h: '8. Your choices',
    b: 'You can edit your profile, change your visibility, clear Nova’s memory, or delete your account at any time from Settings. If you have questions about your data, contact us through the app.',
  },
  {
    h: '9. Changes',
    b: `We’ll update this policy as the app changes and revise the date below. Last updated: ${LAST_UPDATED}.`,
  },
]

function Doc({ icon: Icon, title, sections, open, onToggle }) {
  return (
    <View style={{ borderRadius: 14, borderWidth: 1, borderColor: C.lineMid, backgroundColor: C.card, marginBottom: 10, overflow: 'hidden' }}>
      <Pressable
        onPress={onToggle}
        style={{ flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 15 }}
      >
        <Icon size={18} color={C.violet} strokeWidth={2.2} />
        <Text style={{ flex: 1, fontFamily: F.semibold, fontSize: 14.5, color: C.ink }}>{title}</Text>
        {open ? <ChevronDown size={18} color={C.faint} strokeWidth={2.2} /> : <ChevronRight size={18} color={C.faint} strokeWidth={2.2} />}
      </Pressable>
      {open && (
        <View style={{ paddingHorizontal: 16, paddingBottom: 16, paddingTop: 2 }}>
          <Text style={{ fontFamily: F.body, fontSize: 11, color: C.faint, marginBottom: 14 }}>Last updated: {LAST_UPDATED}</Text>
          {sections.map((s) => (
            <View key={s.h} style={{ marginBottom: 14 }}>
              <Text style={{ fontFamily: F.semibold, fontSize: 12.5, color: C.ink2 || C.ink, marginBottom: 4 }}>{s.h}</Text>
              <Text style={{ fontFamily: F.body, fontSize: 12.5, color: C.dim, lineHeight: 19 }}>{s.b}</Text>
            </View>
          ))}
        </View>
      )}
    </View>
  )
}

export default function LegalDocs() {
  const [open, setOpen] = useState(null) // 'terms' | 'privacy' | null
  return (
    <View>
      <Doc
        icon={FileText}
        title="Terms & Conditions"
        sections={TERMS}
        open={open === 'terms'}
        onToggle={() => setOpen(open === 'terms' ? null : 'terms')}
      />
      <Doc
        icon={Shield}
        title="Privacy Policy"
        sections={PRIVACY}
        open={open === 'privacy'}
        onToggle={() => setOpen(open === 'privacy' ? null : 'privacy')}
      />
    </View>
  )
}

// Web-only navigation helper for the standalone public pages.
const goTo = (path) => {
  if (Platform.OS === 'web' && typeof window !== 'undefined') window.location.assign(path)
}

// Standalone, no-login legal page served at /terms and /privacy so the documents
// can be linked from an app-store listing or a marketing site. `doc` is
// 'terms' | 'privacy'.
export function LegalPage({ doc }) {
  const isTerms = doc === 'terms'
  const sections = isTerms ? TERMS : PRIVACY
  const title = isTerms ? 'Terms & Conditions' : 'Privacy Policy'
  const Icon = isTerms ? FileText : Shield
  return (
    <View style={{ flex: 1, backgroundColor: C.bg }}>
      <ScrollView contentContainerStyle={{ paddingHorizontal: 24, paddingTop: 60, paddingBottom: 80, maxWidth: 720, width: '100%', alignSelf: 'center' }}>
        <Pressable onPress={() => goTo('/')} hitSlop={8} style={{ marginBottom: 20 }}>
          <Text style={{ fontFamily: F.semibold, fontSize: 13, color: C.violet }}>← NorthStar</Text>
        </Pressable>

        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 6 }}>
          <Icon size={22} color={C.violet} strokeWidth={2.2} />
          <Text style={{ fontFamily: F.display, fontSize: 26, color: C.ink, letterSpacing: 1 }}>{title}</Text>
        </View>
        <Text style={{ fontFamily: F.body, fontSize: 12, color: C.faint, marginBottom: 26 }}>Last updated: {LAST_UPDATED}</Text>

        {sections.map((s) => (
          <View key={s.h} style={{ marginBottom: 18 }}>
            <Text style={{ fontFamily: F.semibold, fontSize: 14.5, color: C.ink2 || C.ink, marginBottom: 6 }}>{s.h}</Text>
            <Text style={{ fontFamily: F.body, fontSize: 13.5, color: C.dim, lineHeight: 21 }}>{s.b}</Text>
          </View>
        ))}

        <View style={{ flexDirection: 'row', gap: 18, marginTop: 20, paddingTop: 20, borderTopWidth: 1, borderTopColor: C.lineMid }}>
          <Pressable onPress={() => goTo(isTerms ? '/privacy' : '/terms')} hitSlop={6}>
            <Text style={{ fontFamily: F.semibold, fontSize: 13, color: C.violet }}>{isTerms ? 'Privacy Policy' : 'Terms & Conditions'}</Text>
          </Pressable>
          <Pressable onPress={() => goTo('/')} hitSlop={6}>
            <Text style={{ fontFamily: F.semibold, fontSize: 13, color: C.faint }}>Back to app</Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  )
}
